batchsize: 10
bos_token: 1
channels: 1
debug: false
decoder_args: 
  cross_attend: true
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
device: cuda
dim: 256
encoder_depth: 4
eos_token: 2
heads: 8
backbone_layers:
- 2
- 3
- 7
max_dimensions:
- 672
- 192
min_dimensions:
- 96
- 32
max_height: 192
max_seq_len: 512
max_width: 672
num_layers: 4
num_tokens: 8000
pad: false
pad_token: 0
patch_size: 16
temperature: 0.2
tokenizer: dataset/tokenizer.json
